version: "3.9"
services:

  app:
      build: .
      env_file:
        - .env
      environment:
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - DBNAME=${DBNAME}
        - DBHOST=db
      depends_on:
        db:
          condition: service_healthy
      links:
        - db
      ports:
        - 8080:8080

  db:
    image: postgres:latest
    env_file:
        - .env
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
        interval: 5s
        timeout: 5s
        retries: 5